apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  # Nazwa Deploymentu frontend.
  name: frontend
  # Przestrzeń nazw frontend.
  namespace: frontend
spec:
  # Liczba replik Deploymentu frontend ustawiona na 3.
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      # Node Affinity: Zapewnia, że pody Deploymentu nie trafą na węzły dedykowane dla Deploymentu backend i poda my-sql.
      # Operator NotIn wyklucza węzeł oznaczony jako zone=backend.
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zone
                operator: NotIn
                values:
                - backend
      containers:
      # Obraz nginx dla Deploymentu frontend.
      - image: nginx
        name: nginx
        # Zasoby: Niezbędne do działania przy włączonym ResourceQuota.
        # 100m CPU pozwala na uruchomienie dokładnie 10 replik w ramach limitu 1 CPU.
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
status: {}
