apiVersion: v1
kind: Pod
metadata:
  name: load-generator
  namespace: backend
  # Etykieta 'app: backend' jest wymagana, aby NetworkPolicy frontendu dopuściła ruch z tego poda.
  labels:
    app: backend
spec:
  restartPolicy: Never
  containers:
  - name: load-generator
    image: busybox:1.28
    # Uruchomienie 4 równoległych procesów wget w celu wygenerowania
    # wystarczającego obciążenia CPU do wyzwolenia HPA.
    command:
      - /bin/sh
      - -c
      # Użyta jest pełna nazwa DNS usługi
      # ponieważ pod znajduje się w innej przestrzeni nazw – skrócona nazwa działa
      # tylko w obrębie tej samej namespace.
      - |
        while true; do wget -q -O- http://frontend-svc.frontend.svc.cluster.local &>/dev/null; done &
        while true; do wget -q -O- http://frontend-svc.frontend.svc.cluster.local &>/dev/null; done &
        while true; do wget -q -O- http://frontend-svc.frontend.svc.cluster.local &>/dev/null; done &
        while true; do wget -q -O- http://frontend-svc.frontend.svc.cluster.local &>/dev/null; done &
        wait
    # Zdefiniowanie resources jest wymagane przez ResourceQuota w przestrzeni nazw backend.
    resources:
      requests:
        cpu: 50m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 100Mi